FROM openjdk:8
ADD target/menu-microserice-product-type-0.0.1-SNAPSHOT.jar menu-microserice-product-type-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "menu-microserice-product-type-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
