FROM openjdk:8
ADD target/menu-microservice-product-0.0.1-SNAPSHOT.jar menu-microservice-product-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "menu-microservice-product-0.0.1-SNAPSHOT.jar"]
EXPOSE 8080
